	<div class="row" id="structDiv">
		<div class="col-lg-8 col-lg-offset-2">
			<div class="panel panel-info">
				<div class=" h2 panel-heading nav">
					<div class="navbar-left">Cadastro de Estrutura do Plano de Contas</div>
				</div>
				<div class="panel-body struct-panel">
					<div class="col-lg-6">
						<div class="panel-structure">	
							<div id="structTree"></div>
						</div>
					</div>
					<div class="col-lg-6">
						<?php
							 echo $this->form()->openTag($form);

						?>
						<div class="form-group">
							<label for="company">Empresa</label>
							<div class="input-group">
								<?php 
									echo $this->formSelect($form->get('company'));
								?>
								<span class="input-group-btn">
									<a href="<?= $this->url('application',['controller'=>'Company','action'=>'register']); ?>" class="btn btn-info"><span class="glyphicon glyphicon-plus" title="Novo Banco"></span></a>
								</span>
							</div>					
						</div>

						<div class="form-group">
							<label for="company">Item</label>
							<div class="input-group">
								<?php 
									echo $this->formSelect($form->get('item'));
								?>
								<span class="input-group-btn">
									<a href="<?= $this->url('finance',['controller'=>'StructureItem','action'=>'register']); ?>" class="btn btn-info"><span class="glyphicon glyphicon-plus" title="Novo Banco"></span></a>
								</span>
							</div>					
						</div>

						<div class="form-group">
							<label for="name">Dependência</label>
							<?php
								echo $this->formInput($form->get('inherit'));
							?>
							<div class="text-danger"><?php  echo $this->formElementErrors()->render($form->get('inherit')); ?></div>
						</div>

						<?php
							echo $this->formInput($form->get('inheritId'));
							echo $this->formRow($form->get('csrf'));
						?>

						<input type="submit" value="Salvar" class="btn btn-info">
						<a href="<?= $this->url('finance',['controller'=>'Structure','action'=>'Index']); ?>" class="btn btn-warning">Cancelar</a>

						<?php 
							echo $this->form()->closeTag();
						?>
					</div>
				</div>
			</div>
		</div>
	</div>