<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
			<div class=" h2 panel-heading">Cadastro de Agência</div>
			<div class="panel-body">
				<?php
				 	echo $this->form()->openTag($form);

				?>

				<div class="form-group">
					<label for="bank">Banco</label>
					<div class="input-group">
						<?php 
							echo $this->formSelect($form->get('bank'));
						?>
						<span class="input-group-btn">
							<a href="<?= $this->url('finance',['controller'=>'Bank','action'=>'register']); ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Novo Banco">
								<span class="glyphicon glyphicon-plus"></span>
							</a>
						</span>
					</div>					
				</div>

				<div class="form-group">
					<label for="name">Nome</label>
					<?php
						echo $this->formInput($form->get('name'));
					?>
					<div class="text-danger"><?php  echo $this->formElementErrors()->render($form->get('name')); ?></div>
				</div>

				<div class="form-group">
					<label for="number">Número</label>
					<?php
						echo $this->formInput($form->get('number'));
						echo $this->formElementErrors()->render($form->get('number'));
					?>
				</div>

				<?php
					echo $this->formRow($form->get('csrf'));
				?>

				<input type="submit" value="Salvar" class="btn btn-primary">
				<a href="<?= $this->url('finance',['controller'=>'Agency','action'=>'Index']); ?>" class="btn btn-primary">Cancelar</a>

				<?php 
					echo $this->form()->closeTag();
				?>

			</div>
		</div>
	</div>
</div>