<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Cadastro de Tipo de Conta</div>
			<div class="panel-body">
				<form method="post" action="<?= $this->url('finance', ['controller'=>'AccountType','action'=>'delete']) ?>">
					<input type="hidden" value="<?= $accountType->getId(); ?>" name ="id">
					<p class="alert alert-danger" >Deseja realmente remover esse tipo de conta? <strong><?= $accountType->getName(); ?></strong> da lista?</p>
					<input type="submit" value="Sim" class="btn btn-danger"></input>
					<a href="<?= $this->url('finance',['controller'=>'AccountType','action'=>'Index']); ?>" class="btn btn-primary">Não</a>
				</form>
			</div>
		</div>
	</div>
</div>