<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
			<div class=" h2 panel-heading">Cadastro de Contas</div>
			<div class="panel-body">

				<?php
				 	echo $this->form()->openTag($form);
				?>

				<div class="form-group">
					<label for="company">Empresa</label>
					<div class="input-group">
							<?php 
								echo $this->formSelect($form->get('company'));
							?>
	      				<span class="input-group-btn">
							<a href="<?= $this->url('application',['controller'=>'Company','action'=>'register']); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus" title="Nova Empresa"></span></a>
						</span>
					</div>
				</div>

				<div class="form-group">
					<label for="bank">Banco</label>
					<div class="input-group">
						<?php 
							echo $this->formSelect($form->get('bank'));
						?>
	      				<span class="input-group-btn">
							<a href="<?= $this->url('finance',['controller'=>'Bank','action'=>'register']); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus" title="Novo Banco"></span></a>
						</span>
					</div>
				</div>

				<div class="form-group">
					<label for="agency">Agência</label>
					<div class="input-group">					
						<?php
							echo $this->formSelect($form->get('agency'));
						?>
	      				<span class="input-group-btn">
							<a href="<?= $this->url('finance',['controller'=>'Agency','action'=>'register']); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus" title="Nova Agência"></span></a>
						</span>
					</div>
				</div>				

				<div class="form-group">
					<label for="number">Número</label>
						<?php
							echo $this->formInput($form->get('number'));
							echo $this->formElementErrors()->render($form->get('number'));
						?>
				</div>

				<div class="form-group">
					<label for="accountType">Banco</label>
					<div class="input-group">					
						<?php 
							echo $this->formSelect($form->get('accountType'));
						?>
	      				<span class="input-group-btn">
							<a href="<?= $this->url('finance',['controller'=>'Agency','action'=>'register']); ?>" class="btn btn-primary"><span class="glyphicon glyphicon-plus" title="Nova Agência"></span></a>
						</span>
					</div>
				</div>

				<?php
					echo $this->formRow($form->get('csrf'));
				?>

				<input type="submit" value="Salvar" class="btn btn-primary">
				<a href="<?= $this->url('finance',['controller'=>'Account','action'=>'Index']); ?>" class="btn btn-primary">Cancelar</a>

				<?php 
					echo $this->form()->closeTag();
				?>

			</div>
		</div>
	</div>
</div>