<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading nav">
				<div class="navbar-left">Orçamentos</div>
				<div class="navbar-right">
					<a href="<?= $this->url('commercial',['controller' => 'Budget','action' => 'register']) ?>" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="Cadastrar novo Orçamento">
						<span class="glyphicon glyphicon-plus"></span>
					</a>
				</div>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Contato</th>
							<th>Email</th>
							<th>Serviço</th>
						</tr>
					</thead>
					<tbody>
						<?php
							foreach($budgets as $bud){
						?>
							<tr>
								<td><?= $bud->getContact();?></td>
								<td><?= $bud->getEmail();?></td>
								<td><?= $bud->getService();?></td>
								<td>
									<a href="<?= $this->url('commercial', ['controller' => 'Budget','action' =>'delete', 'id' => $bud->getId()]) ?>" class="btn btn-danger" data-toggle="tooltip" data-placement="left" title="Remover Orçamento">
										<span class="glyphicon glyphicon-trash"></span>
									</a>
									<a href="<?= $this->url('commercial', ['controller' => 'Budget','action' =>'update', 'id' => $bud->getId()]) ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Alterar Orçamento">
										<span class="glyphicon glyphicon-pencil"></span>
									</a>
									</td>
								</tr>
							<?php
							} 
							?>	
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
			

  <?php
#echo $this->PaginationHelper($produtos,$qtdPorPagina,'/Produtos');
?>