<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Orçamentos</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Contato</th>
							<th>Email</th>
							<th>Serviço</th>
						</tr>
					</thead>
					<tbody>
						<?php
							foreach($budgets as $bud){
						?>
							<tr>
								<td><?= $bud->getContact();?></td>
								<td><?= $bud->getEmail();?></td>
								<td><?= $bud->getService();?></td>
								<td>
									<a href="<?= $this->url('commercial', ['controller' => 'Budget','action' =>'delete', 'id' => $bud->getId()]) ?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash" title="Excluir"></span></a>
									<a href="<?= $this->url('commercial', ['controller' => 'Budget','action' =>'update', 'id' => $bud->getId()]) ?>" class="btn btn-primary"><span class="glyphicon glyphicon-pencil" title="Alterar"></span></a>
									</td>
								</tr>
							<?php
							} 
							?>	
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
			

  <?php
#echo $this->PaginationHelper($produtos,$qtdPorPagina,'/Produtos');
?>