<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h1>Cadastro de Orçamentos</h1>

		 <?php
		 	echo $this->form()->openTag($form);
		 ?>

		<!--<form method="post" action="\Index\cadastrar">-->
		<div class="row">
			
			<div class="form-group col-md-6">
				<label>Cliente</label>
				<?php
					echo $this->formInput($form->get('client'));
					#echo $this->formElementErrors()->render($form->get('nome'));
				?>
			</div>
			<div class="form-group col-md-6">
				<label>Contato</label>
				<?php
					echo $this->formInput($form->get('contact'));
					echo $this->formElementErrors()->render($form->get('contact'));
				?>
			</div>

		</div>
			<div class="form-group">
				<label>Telefone</label>
				<?php
					echo $this->formInput($form->get('phone'));
				?>
			</div>

			<div class="form-group">
				<label>Email</label>
				<?php
					echo $this->formInput($form->get('email'));
				?>
			</div>

			<div class="form-group">
				<label>Localizaão</label>
				<?php
					echo $this->formTextarea($form->get('location'));
				?>
			</div>

			<div class="form-group">
				<label>Cep</label>
				<?php
					echo $this->formInput($form->get('cep'));
				?>
			</div>

				<div class="form-group">
				<label>Serviço</label>
				<?php
					echo $this->formInput($form->get('service'));
				?>
			</div>

				<div class="form-group">
				<label>Descrição</label>
				<?php
					echo $this->formTextarea($form->get('description'));
				?>
			</div>

			<?php
				echo $this->formRow($form->get('csrf'));
			?>

			<div class="form-group">
				<input type="submit" value="Salvar" class="btn btn-primary">
			</div>
			<?php 
				echo $this->form()->closeTag();
			?>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>