<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Cadastro de Orçamento</div>
			<div class="panel-body">

				 <?php
				 	echo $this->form()->openTag($form);
				 ?>

				<!--<form method="post" action="\Index\cadastrar">-->
				<div class="row">
					
					<div class="form-group col-md-6">
						<label>Cliente</label>
						<?php
							echo $this->formInput($form->get('client')->setValue($budget->getClient()));
							#echo $this->formElementErrors()->render($form->get('nome'));
						?>
					</div>
					<div class="form-group col-md-6">
						<label>Contato</label>
						<?php
							echo $this->formInput($form->get('contact')->setValue($budget->getContact()));
							echo $this->formElementErrors()->render($form->get('contact'));
						?>
					</div>

				</div>
				<div class="row">
					<div class="form-group col-lg-6">
						<label>Telefone</label>
						<?php
							echo $this->formInput($form->get('phone')->setValue($budget->getPhone()));
						?>
					</div>

					<div class="form-group col-lg-6">
						<label>Email</label>
						<?php
							echo $this->formInput($form->get('email')->setValue($budget->getEmail()));
						?>
					</div>
				</div>

					<div class="form-group">
						<label>Localização</label>
						<?php
							echo $this->formTextarea($form->get('location')->setValue($budget->getLocation()));
						?>
					</div>

					<div class="form-group">
						<label>Cep</label>
						<?php
							echo $this->formInput($form->get('cep')->setValue($budget->getCep()));
						?>
					</div>

					<div class="form-group">
						<label>Serviço</label>
						<?php
							echo $this->formInput($form->get('service')->setValue($budget->getService()));
						?>
					</div>

					<div class="form-group">
						<label>Descrição</label>
						<?php
							echo $this->formTextarea($form->get('description')->setValue($budget->getDescription()));
						?>
					</div>

					<?php
						echo $this->formRow($form->get('csrf'));
					?>

					<input type="submit" value="Atualizar" class="btn btn-primary">
					<a href="<?= $this->url('commercial',['controller'=>'Budget','action'=>'Index']); ?>" class="btn btn-primary">Cancelar</a>

					<?php 
						echo $this->form()->closeTag();
					?>
			</div>
		</div>
	</div>
</div>