<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h1>Editar Orçamentos</h1>

		 <?php
		 	echo $this->form()->openTag($form);
		 ?>

		<!--<form method="post" action="\Index\cadastrar">-->
		<div class="row">
			
			<div class="form-group col-md-6">
				<label>Cliente</label>
				<?php
					echo $this->formInput($form->get('client')->setValue($budget->getClient()));
					#echo $this->formElementErrors()->render($form->get('nome'));
				?>
			</div>
			<div class="form-group col-md-6">
				<label>Contato</label>
				<?php
					echo $this->formInput($form->get('contact')->setValue($budget->getContact()));
					echo $this->formElementErrors()->render($form->get('contact'));
				?>
			</div>

		</div>
			<div class="form-group">
				<label>Telefone</label>
				<?php
					echo $this->formInput($form->get('phone')->setValue($budget->getPhone()));
				?>
			</div>

			<div class="form-group">
				<label>Email</label>
				<?php
					echo $this->formInput($form->get('email')->setValue($budget->getEmail()));
				?>
			</div>

			<div class="form-group">
				<label>Localizaão</label>
				<?php
					echo $this->formTextarea($form->get('location')->setValue($budget->getLocation()));
				?>
			</div>

			<div class="form-group">
				<label>Cep</label>
				<?php
					echo $this->formInput($form->get('cep')->setValue($budget->getCep()));
				?>
			</div>

				<div class="form-group">
				<label>Serviço</label>
				<?php
					echo $this->formInput($form->get('service')->setValue($budget->getService()));
				?>
			</div>

				<div class="form-group">
				<label>Descrição</label>
				<?php
					echo $this->formTextarea($form->get('description')->setValue($budget->getDescription()));
				?>
			</div>

			<?php
				echo $this->formRow($form->get('csrf'));
			?>

			<div class="form-group">
				<input type="submit" value="Atualizar" class="btn btn-primary">
			</div>
			<?php 
				echo $this->form()->closeTag();
			?>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>