<?php 
	$url = $this->url('application',['controller' => 'User','action' => 'login']);
?>
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">Login</div>
			<div class="panel-body">
				<form action="<?= $url; ?>" method="post">
					<div class="form-group">
						<label for="userName">Usuario:</label>
						<input type="text" id="userName" name="userName" class="form-control">
					</div>

					<div class="form-group">
						<label for="password">Senha:</label>
						<input type="password" id="password" name="password" class="form-control">
					</div>

					<div class="form-group">
						<input type="submit" value="Entrar" class="btn btn-primary">
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-4"></div>
</div>