<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Cadastro de Fornecedor</div>
			<div class="panel-body">
				<form method="post" action="<?= $this->url('purchase', ['controller'=>'Provider','action'=>'delete']) ?>">
					<input type="hidden" value="<?= $provider->getId(); ?>" name ="id">
					<p class="alert alert-danger" >Deseja realmente remover o fornecedor <strong><?= $provider->getNickName(); ?></strong> da lista?</p>
					<input type="submit" value="Sim" class="btn btn-danger"></input>
					<a href="<?= $this->url('purchase',['controller'=>'Provider','action'=>'Index']); ?>" class="btn btn-primary">Não</a>
				</form>
			</div>
		</div>
	</div>
</div>