<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h1>Empresas</h1>

		<table class="table table-striped">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Cnpj</th>
					<th>Inscrição Municipal</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<?php 
					foreach ($companys as $c) {
				?>
				<tr>
					<td><?= $c->getNickName(); ?></td>
					<td><?= $c->getCnpj(); ?></td>
					<td><?= $c->getIm(); ?></td>
					<td>
						<a href="<?= $this->url('application',['Controller' => 'Company','action' => 'delete','id' => $c->getId()]) ?>" class="btn btn-danger">Remover</a>
						<a href="<?= $this->url('application',['Controller' => 'Company','action' => 'update','id' => $c->getId()]) ?>" class="btn btn-info">Editar</a>
					</td>
				</tr>

				<?php
					}
				 ?>
			</tbody>
		</table>
	</div>
	<div class="col-md-3"></div>
</div>
