<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Empresas</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr>
							<th class="text-primary">Nome</th>
							<th class="text-primary">Cnpj</th>
							<th class="text-primary">Inscrição Municipal</th>
						</tr>
					</thead>
					<tbody>
						<?php 
							foreach ($companys as $c) {
						?>
						<tr>
							<td><?= $c->getNickName(); ?></td>
							<td><?= $c->getCnpj(); ?></td>
							<td><?= $c->getIm(); ?></td>
							<td>
								<a href="<?= $this->url('application', ['controller' => 'Company','action' =>'delete', 'id' => $c->getId()]) ?>" class="btn btn-danger" data-toggle="tooltip" data-placement="left" title="Excluir Empresa"><span class="glyphicon glyphicon-trash"></span></a>
								<a href="<?= $this->url('application', ['controller' => 'Company','action' =>'update', 'id' => $c->getId()]) ?>" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Alterar Empresa"><span class="glyphicon glyphicon-pencil"></span></a>
							</td>
						</tr>
						<?php
							}
						 ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
