<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<div class="panel panel-primary">
		<!--<h1 class="alert alert-info">Empresas</h1>-->
			<div class=" h2 panel-heading">Cadastro de Empresa</div>
			<div class="panel-body">
		
				 <?php
				 	echo $this->form()->openTag($form);
				 ?>

				<div class="row">
					<div class="form-group col-lg-5">
						<label>Nome</label>
						<?php
							echo $this->formInput($form->get('nickName')->setValue($company->getNickName()));
						?>
						<div class="text-danger"><?php  echo $this->formElementErrors()->render($form->get('nickName')); ?></div>
						

					</div>

					<div class="form-group col-lg-7">
						<label>Razão Social</label>
						<?php
							echo $this->formInput($form->get('companyName')->setValue($company->getCompanyName()));
							echo $this->formElementErrors()->render($form->get('companyName'));
						?>
					</div>
				</div>

				<div class="row">
					<div class="form-group col-lg-4">
						<label>CNPJ</label>
						<?php
							echo $this->formInput($form->get('cnpj')->setValue($company->getCnpj()));
							echo $this->formElementErrors()->render($form->get('cnpj'));
						?>
					</div>

					<div class="form-group col-lg-4">
						<label>Inscrição Estadual</label>
						<?php
							echo $this->formInput($form->get('ie')->setValue($company->getIe()));
							echo $this->formElementErrors()->render($form->get('ie'));
						?>
					</div>

					<div class="form-group col-lg-4">
						<label>Inscrição Municipal</label>
						<?php
							echo $this->formInput($form->get('im')->setValue($company->getIm()));
							echo $this->formElementErrors()->render($form->get('im'));
						?>
					</div>
				</div>
				<div class="row">
					<div class="form-group col-lg-10">
						<label>Endereço</label>
						<?php
							echo $this->formInput($form->get('street')->setValue($company->getStreet()));
							echo $this->formElementErrors()->render($form->get('street'));
						?>
					</div>

					<div class="form-group col-lg-2">
						<label>Número</label>
						<?php
							echo $this->formInput($form->get('number')->setValue($company->getNumber()));
							echo $this->formElementErrors()->render($form->get('number'));
						?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-5 form-group ">
						<label>Bairro</label>
						<?php
							echo $this->formInput($form->get('neighborhood')->setValue($company->getNeighborhood()));
							echo $this->formElementErrors()->render($form->get('neighborhood'));
						?>
					</div>

					<div class="col-lg-5 form-group">
						<label>Cidade</label>
						<?php
							echo $this->formInput($form->get('city')->setValue($company->getCity()));
							echo $this->formElementErrors()->render($form->get('city'));
						?>
					</div>

					<div class="col-lg-2 form-group">
						<label>Estado</label>
						<?php
							echo $this->formInput($form->get('state')->setValue($company->getState()));
							echo $this->formElementErrors()->render($form->get('state'));
						?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-4 form-group">
						<label>Cep</label>
						<?php
							echo $this->formInput($form->get('cep')->setValue($company->getCep()));
							echo $this->formElementErrors()->render($form->get('cep'));
						?>
					</div>

					<div class="col-lg-4 form-group">
						<label>Telefone</label>
						<?php
							echo $this->formInput($form->get('phone')->setValue($company->getPhone()));
							echo $this->formElementErrors()->render($form->get('phone'));
						?>
					</div>

					<div class="col-lg-4 form-group">
						<label>Email</label>
						<?php
							echo $this->formInput($form->get('email')->setValue($company->getEmail()));
						?>
						<div class="text-danger"><?php echo $this->formElementErrors()->render($form->get('email')); ?></div>
					</div>
				</div>

				<?php
					echo $this->formRow($form->get('csrf'));
				?>
				
				<input type="submit" value="Atualizar" class="btn btn-primary">
				<a href="<?= $this->url('application',['controller'=>'Company','action'=>'Index']); ?>" class="btn btn-primary">Cancelar</a>

				<?php 
					echo $this->form()->closeTag();
				?>

			</div>
		</div>
	</div>
</div>